import Head from "next/head";
import Euler from "../public/euler.jpg"
import s from "../styles/Home.module.css";
import Image from "next/image";

const Home = () => (
	<>
		<Head>
			<title>Generated by create next app</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<h1>Project Euler</h1>
		<div className={s.euler}>
			<p>“It is mathematics that gives the most reliable rules: whoever follows them is not dangerous to deceive the senses.” - Leonard Euler</p>
			<Image src={Euler} alt='euler' className={s.imgEuler} />
		</div>
	</>
);

export default Home;
