import { useState } from "react";
import s from "../../styles/Project.module.css";

const ProjectData = [
	{
		title: "Project 1: Multiples of 3 or 5",
		task: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/1/main.js",
		resolve: "233168",
	},
	{
		title: "Project 2: Even Fibonacci numbers",
		task: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/2/main.js",
		resolve: "4613732",
	},
	{
		title: "Project 3: Largest prime factor",
		task: "The prime factors of 13195 are 5, 7, 13 and 29.What is the largest prime factor of the number 600851475143 ?",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/3/main.js",
		resolve: "Look at the code 🠗",
	},
	{
		title: "Project 4: Largest palindrome product",
		task: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/4/main.js",
		resolve: "906609",
	},
	{
		title: "Project 5: Smallest multiple",
		task: "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/5/main.js",
		resolve: "232792560",
	},
	{
		title: "Project 6: Sum square difference",
		task: "The sum of the squares of the first ten natural numbers is, 1² + 2² + ... + 10² = 385 The square of the sum of the first ten natural numbers is (1 + 2 + ... + 10²)² = 55² = 3025, Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is. 3025 - 385 = 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/6/main.js",
		resolve: "25164150",
	},
	{
		title: "Project 7: 10001st prime",
		task: "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/7/main.js",
		resolve: "104743",
	},
	{
		title: "Project 8: Largest product in a series",
		task: 'The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.\n73167176531330624919225119674426574742355349194934\n96983520312774506326239578318016984801869478851843\n85861560789112949495459501737958331952853208805511\n12540698747158523863050715693290963295227443043557\n66896648950445244523161731856403098711121722383113\n62229893423380308135336276614282806444486645238749\n30358907296290491560440772390713810515859307960866\n70172427121883998797908792274921901699720888093776\n65727333001053367881220235421809751254540594752243\n52584907711670556013604839586446706324415722155397\n53697817977846174064955149290862569321978468622482\n83972241375657056057490261407972968652414535100474\n82166370484403199890008895243450658541227588666881\n16427171479924442928230863465674813919123162824586\n17866458359124566529476545682848912883142607690042\n24219022671055626321111109370544217506941658960408\n07198403850962455444362981230987879927244284909188\n84580156166097919133875499200524063689912560717606\n05886116467109405077541002256983155200055935729725\n71636269561882670428252483600823257530420752963450\nFind the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?',
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/8/main.js",
		resolve: "23514624000",
	},
	{
		title: "Project 9: 	Special Pythagorean triplet",
		task: "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a² + b² = c². For example, 3² + 4² = 9 + 16 = 25 = 5². There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/9/main.js",
		resolve: "31875000",
	},
	{
		title: "Project 10: Summation of primes",
		task: "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below two million.",
		link: "https://github.com/TheSnegok/ProjectEuler/blob/main/10/main.js",
		resolve: "142913828922",
	},
];

const Project = ({ number }) => {
	const [show, unShow] = useState(false);

	return (
		<div className={s.project}>
			<h1 className={s.title}>{ProjectData[number].title}</h1>
			<p className={s.headerTask}>Task:</p>
			<p className={s.task}>{ProjectData[number].task}</p>
			<p className={s.resolve}>Resolve:</p>
			<div
				onClick={() => unShow(true)}
				className={show ? s.show : s.spoiler}
			>
				<p className={show ? s.answer : s.blurAnswer}>
					{ProjectData[number].resolve}
				</p>
			</div>
			<p className={s.code}>Code:</p>
			<div className={s.link}>
				<a href={ProjectData[number].link}>
					{ProjectData[number].link}
				</a>
			</div>
		</div>
	);
};

export default Project;
